detectors:
  DataClump:
    exclude:
      - Sinatra::Param::Helpers
  DuplicateMethodCall:
    max_calls: 3
  IrresponsibleModule:
    enabled: false
  ManualDispatch:
    exclude:
      - Sinatra::Param#self.registered
