require:
  - rubocop-rspec

Metrics/ClassLength:
  Exclude:
    - spec/dummy/app.rb

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
